### PR TITLE
feat!: implement directives

### LINKED ISSUE #9: Implement Directives grammar
[Directives | TypeSpec](https://typespec.io/docs/language-basics/directives/)

It seems that `#deprecated` and `#suppress` are documented for now.
Now it seems that the parser is partially broken if `#` is included.
The semantic one should be handled by LSP, so we should just deal with it in a messy and sharp way.

I will try to see if I can implement it.

### PR DESCRIPTION
**Pull request by ncaq**
Allow decorators and directives to be read in no particular order.
It was necessary to put the two together in annotation to be out of order.

### CODE REVIEW

**Comment by ncaq** [comment]
@happenslol 
Was there something wrong with this PR?
I've created a new ANOTATION data structure, but I don't see any way to make it syntactically good no matter which comes first, the directives or the decorators.

**Comment by happenslol** [comment]
Hi, sorry but I've been busy for a few days and haven't had the time to look at this yet. I should be able to have a look today or tomorrow 👍

**Comment by ncaq** [comment]
Thank you for taking the time to respond.
Thank you very much for your time.

**Comment by happenslol** [comment]
From what I can see this allows any order of decorators and directives in a list, so something like `#directive @decorator @decorator2 #directive2` would be allowed. Is that intentional?

I'm also fine with being a bit looser than the official spec here to keep highlighting working, I'm just interested whether the spec talks about this at all.

**Comment by ncaq** [comment]
When I was implementing it, I thought it would be okay to require that the directives always come first.
However, looking at the official Example, I could not immediately determine the order of decorators and directives, so I decided it would be better to write a forgiving parser.
I thought it would be better to write a permissive parser, since the main purpose of the parser is to highlight syntax, not to analyze errors, so I thought it would be OK to tolerate some incorrect syntax in practice.
Personally, I think that error reporting on the fly can be left to lsp.

**Comment by happenslol** [comment]
Yeah, I agree with you, being more permissive is definitely fine here.

If you rebase on latest master, I'll approve and merge :+1:

**Comment by ncaq** [comment]
@happenslol 
I rebase now.

**Pull request merged**
