### PR TITLE
Move parens inside function_parameter_list

### LINKED ISSUE #3: Include parents in function, decorator bodies
I customized the [highlights.scm](https://github.com/heaths/helix/blob/main/runtime/queries/typespec/highlights.scm) for my [Helix](https://github.com/helix-editor/helix) language support for TypeSpec and noticed that functions' and decorators' bodies are inconsistent with operations' body when it comes to including `()`. Compared to other language support in Helix, a gesture like `mif` (select inside function) or `mit` (select inside type) includes the parents/brackets but this does not seem achievable with functions and decorators because the parens are not part of the parameter list token.

I'm happy to submit a PR if you're open to having them included like they are for operations' body / param list.

[asciicast](https://asciinema.org/a/VkGbOYkrgohBboBVDTnGQkiLB)

### PR DESCRIPTION
**Pull request by heaths**
Fixes #3

### CODE REVIEW

**Comment by heaths** [comment]
Tested successfully along with heaths/helix#3

**Comment by happenslol** [comment]
Thank you! Can you add an example to the `test/corpus/statements.txt` file so that we can track the resulting AST changes from this?

**Comment by heaths** [comment]
I started doing that, actually, and couldn't find documentation on https://typespec.io for functions. I'll talk with the lead about that. For now, I can just base the sample on the grammar alone. /cc @bterlson

**Comment by heaths** [comment]
I found that the identifier was missing based on their `grammar.js` and <https://github.com/microsoft/typespec/blob/0fbfced6c4d43e68f4bcc6852cabc72c25a8908f/packages/website/versioned_docs/version-latest/standard-library/reference/js-api/interfaces/FunctionDeclarationStatementNode.md?plain=1#L11>. I'll fix that as well.

**Comment by happenslol** [comment]
Great, looks good to me! If you're done with this, just give me a thumbs up and I can merge anytime.

**Review by happenslol — APPROVED** [review]

**Comment by heaths** [comment]
Done with this aspect. If I find anything else, I'm happy to open PRs as needed. That said, I think this covers the use cases in helix I wanted to support for now.

**Comment by heaths** [comment]
@happenslol do you feel confident / happy with the current implementation? I was thinking of submitting a PR to helix-editor/helix to include this by default along with my stuff in <https://github.com/heaths/helix/tree/main/runtime/queries/typespec>.

Looks like a PR to <https://github.com/helix-editor/helix/blob/master/languages.toml> would be enough.

**Comment by happenslol** [comment]
Yeah, for sure! The current implementation doesn't handle the values syntax introduced in the newest updates, but apart from that I'm confident in it and it's well tested. It's already included in nvim-treesitter, so you're good to include it from my end!

**Comment by heaths** [comment]
We'll see if it passes their usage litmus test. It's not quite there for linguist/GitHub...yet.

**Comment by happenslol** [comment]
> We'll see if it passes their usage litmus test. It's not quite there for linguist/GitHub...yet.

Alright, keep me in the loop. What's the requirement for GitHub? Anything I can do? Or is it just a treesitter thing in general?

**Pull request merged**
